[package]
name = "rust-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
log = "0.4.17"
serde ={version = "1.0.197", features = ["derive"]}
serde_json = "1.0.128"
env_logger = "0.11.5"
tokio-postgres = "0.7.7"

[dev-dependencies]
actix-rt = "2.7.0"
